### ISSUE TITLE
Unable to do anything when pressing the show mouse cursor key

### ISSUE THREAD

**Issue by AuroraTransporter** [Rusketh/SatifactoryCalculatorMod#1]
Hello, i have an issue where when you press the Show Mouse Cursor Key the game wont let you do anything. Attempting to press the key again will not do anything and clicking the mouse will just remove the cursor. I have tested it with no other mods than this one and the issue persists.

Let me know if there is anything i can do to help.

**Comment by Rusketh** [comment]
Have you tried pressing F6?

**Comment by AuroraTransporter** [comment]
Yes that's what I mean I have tried that and it does nothing

**Comment by Rusketh** [comment]
This should now be resolved, I have added a button to turn it off.
